In [22]:
import pandas as pd

#load the dataset
df=pd.read_csv("/content/sample_data/Dataset.csv")
df.head()

,Category,Category-href,Subcat,Subcat-href,name,stars,price
0,Programming & Tech,https://www.fiverr.com/categories/programming-...,Data Analysis & Reports,https://www.fiverr.com/categories/programming-...,I will build automated and insightful power bi...,5.0(10),Starting at€137.76
1,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Greeting Cards & Videos,https://www.fiverr.com/categories/lifestyle/gr...,I will get kermit to personalize a video birth...,5.0(1k+),Starting at€4.44
2,Programming & Tech,https://www.fiverr.com/categories/programming-...,Website Builders & CMS,https://www.fiverr.com/categories/programming-...,I will build or redesign your existing squares...,5.0(68),Starting at€66.66
3,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Cooking Lessons,https://www.fiverr.com/categories/lifestyle/co...,I will create original eastern food cooking vi...,4.9(5),Starting at€17.78
4,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Legal Writing,https://www.fiverr.com/categories/writing-tran...,I will write gdpr privacy policy and terms and...,5.0(2),Starting at€8.89

In [17]:
#Rows and Columns
rows,columns=df.shape

print( "The number of rows is:",rows)
print("The number of columns is: ",columns)

The number of rows is: 6183
The number of columns is:  7

In [18]:
#Datatypes found in the dataset
print("\nDatatypes:")
print(df.dtypes)

Datatypes:
Category         object
Category-href    object
Subcat           object
Subcat-href      object
name             object
stars            object
price            object
dtype: object

In [19]:
#Check for missing values
print("\n Missing value per column:")
print(df.isnull().sum())

total_missing=df.isnull().sum().sum()

if total_missing==0:
  print("\nThe dataset is complete. (No missing values)")
else:
  print("\nThe dataset contains ",total_missing," missing values")

 Missing value per column:
Category           0
Category-href      0
Subcat             0
Subcat-href        0
name               0
stars            493
price              0
dtype: int64

The dataset contains  493  missing values

In [21]:
#creating dataset sample

first_15=df.head(15) #stores first the first 15 rows
last_20=df.tail(20)  #stores the last 20 rows

#merging the first 15 and last 20 rows
df.sample= pd.concat([first_15,last_20])

#display the sample dataset
print("/Sample Dataframe:")
display(df.sample)

/Sample Dataframe:

,Category,Category-href,Subcat,Subcat-href,name,stars,price
0,Programming & Tech,https://www.fiverr.com/categories/programming-...,Data Analysis & Reports,https://www.fiverr.com/categories/programming-...,I will build automated and insightful power bi...,5.0(10),Starting at€137.76
1,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Greeting Cards & Videos,https://www.fiverr.com/categories/lifestyle/gr...,I will get kermit to personalize a video birth...,5.0(1k+),Starting at€4.44
2,Programming & Tech,https://www.fiverr.com/categories/programming-...,Website Builders & CMS,https://www.fiverr.com/categories/programming-...,I will build or redesign your existing squares...,5.0(68),Starting at€66.66
3,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Cooking Lessons,https://www.fiverr.com/categories/lifestyle/co...,I will create original eastern food cooking vi...,4.9(5),Starting at€17.78
4,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Legal Writing,https://www.fiverr.com/categories/writing-tran...,I will write gdpr privacy policy and terms and...,5.0(2),Starting at€8.89
5,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,UX Writing,https://www.fiverr.com/categories/writing-tran...,I will provide professional copywrite material...,NaN,Starting at€4.44
6,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Podcast Writing,https://www.fiverr.com/categories/writing-tran...,I will write podcast content and stories,NaN,Starting at€8.89
7,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Email Copy,https://www.fiverr.com/categories/writing-tran...,I will copywrite your customers favorite emails,5.0(57),Starting at€31.11
8,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Legal Writing,https://www.fiverr.com/categories/writing-tran...,I will write a legal terms and gdpr privacy po...,5.0(309),Starting at€48.88
9,Digital Marketing,https://www.fiverr.com/categories/online-marke...,Local SEO,https://www.fiverr.com/categories/online-marke...,I will do local SEO for your website,5.0(4),Starting at€88.88
10,Programming & Tech,https://www.fiverr.com/categories/programming-...,Website Builders & CMS,https://www.fiverr.com/categories/programming-...,I will design and redesign wix website,4.9(305),Starting at€133.32
11,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Celebrity Impersonators,https://www.fiverr.com/categories/lifestyle/ce...,I will record my impersonation sebastion manis...,5.0(11),Starting at€8.89
12,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Online Language LessonsNew,https://www.fiverr.com/categories/writing-tran...,I will be your english teacher or english tuto...,5.0(51),Starting at€4.44
13,Video & Animation,https://www.fiverr.com/categories/video-animat...,Slideshows Videos,https://www.fiverr.com/categories/video-animat...,"I will create amazing photo, video slideshow w...",4.9(336),Starting at€8.89
14,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Product Descriptions,https://www.fiverr.com/categories/writing-tran...,I will create outstanding amazon a plus enhanc...,5.0(57),Starting at€31.11
6163,Programming & Tech,https://www.fiverr.com/categories/programming-...,E-Commerce Development,https://www.fiverr.com/categories/programming-...,I will be your shopify theme developer and sho...,5.0(332),Starting at€88.88
6164,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Craft Lessons,https://www.fiverr.com/categories/lifestyle/cr...,I will all about your car,NaN,Starting at€4.44
6165,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Business Names & Slogans,https://www.fiverr.com/categories/writing-tran...,I will think of 5 original name ideas for your...,4.9(1k+),Starting at€62.21
6166,Music & Audio,https://www.fiverr.com/categories/music-audio?...,Podcast EditingNew,https://www.fiverr.com/categories/music-audio/...,I will edit and master your podcast,5.0(9),Starting at€31.11
6167,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Book & eBook Writing,https://www.fiverr.com/categories/writing-tran...,"I will ghostwrite a perfect german text, ebook...",5.0(70),Starting at€4.44
6168,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Transcripts,https://www.fiverr.com/categories/writing-tran...,I will transcribe english audio or video files...,5.0(64),Starting at€8.89
6169,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Relationship Advice,https://www.fiverr.com/categories/lifestyle/re...,I will be your personal life coach,5.0(3),Starting at€13.33
6170,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Creative Writing,https://www.fiverr.com/categories/writing-tran...,I will write an enthralling professional biogr...,4.9(160),Starting at€8.89
6171,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Website Content,https://www.fiverr.com/categories/writing-tran...,I will be your next copywriter and content cre...,5.0(3),Starting at€4.44
6172,Programming & Tech,https://www.fiverr.com/categories/programming-...,Development for StreamersNew,https://www.fiverr.com/categories/programming-...,I will setup your live stream,5.0(1),Starting at€48.88
6173,Music & Audio,https://www.fiverr.com/categories/music-audio?...,Podcast EditingNew,https://www.fiverr.com/categories/music-audio/...,I will edit your english and german podcast,5.0(9),Starting at€8.89
6174,Video & Animation,https://www.fiverr.com/categories/video-animat...,Spokespersons Videos,https://www.fiverr.com/categories/video-animat...,I will film a professional office spokesperson...,4.9(114),Starting at€26.66
6175,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Gaming,https://www.fiverr.com/categories/lifestyle/ga...,I will help you reach your goal in hearthstone...,5.0(1),Starting at€13.33
6176,Video & Animation,https://www.fiverr.com/categories/video-animat...,Product Photography,https://www.fiverr.com/categories/video-animat...,I will professionally photograph your product,5.0(4),Starting at€8.89
6177,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Gaming,https://www.fiverr.com/categories/lifestyle/ga...,I will professionally coach you in valorant,4.9(21),Starting at€26.66
6178,Video & Animation,https://www.fiverr.com/categories/video-animat...,Animated GIFs,https://www.fiverr.com/categories/video-animat...,I will do unique motion graphics video and ani...,4.8(41),Starting at€39.99
6179,Business,https://www.fiverr.com/categories/business?sou...,Market Research,https://www.fiverr.com/categories/business/mar...,I will compare your business with its competitors,4.9(4),Starting at€355.51
6180,Writing & Translation,https://www.fiverr.com/categories/writing-tran...,Transcripts,https://www.fiverr.com/categories/writing-tran...,I will accurately transcribe audio and video f...,5.0(15),Starting at€8.89
6181,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Cooking Lessons,https://www.fiverr.com/categories/lifestyle/co...,I will film high quality cooking video,5.0(8),Starting at€62.21
6182,Lifestyle,https://www.fiverr.com/categories/lifestyle?so...,Cooking Lessons,https://www.fiverr.com/categories/lifestyle/co...,I will give 1100 cooking HQ videos for social...,4.8(9),Starting at€4.44